name: Bug Report
description: Report a bug in Yes UE FSD
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: When I do X, Y happens instead of Z...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Create AutoDriverComponent
        2. Call MoveToLocation(...)
        3. See error
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: The character should move to the target location...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: The character doesn't move and logs an error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Stack Trace
      description: Any relevant log output or error messages
      placeholder: Paste logs here...
      render: shell
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Plugin Version
      description: Which version of Yes UE FSD are you using?
      placeholder: v0.1.0
    validations:
      required: true

  - type: input
    id: ue-version
    attributes:
      label: Unreal Engine Version
      description: Which version of Unreal Engine?
      placeholder: 5.6.0
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you developing on?
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Affected Module
      options:
        - AutoDriverComponent
        - AutoDriverSubsystem
        - Command System
        - Input Simulation
        - Navigation
        - Editor Tools
        - Build System
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: This started happening after...
    validations:
      required: false
